[package]
name = "fastik"
description = "Fast inverse kinematics library"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["python", "cpp", "benchmark/fastik_rust", "benchmark/fastik_scaling"]

[dependencies]
log = "0.4"
nalgebra = "0.35"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
